apiVersion: 1

datasources:
  - name: BigQuery
    type: grafana-bigquery-datasource
    access: proxy
    isDefault: true
    jsonData:
      authenticationType: jwt
      clientEmail: ${GF_BQ_CLIENT_EMAIL}
      defaultProject: ${GF_BQ_PROJECT_ID}
      tokenUri: https://oauth2.googleapis.com/token
      privateKeyPath: /etc/grafana/google-key.json
    editable: true
