apiVersion: 1

datasources:
  - name: BigQuery
    type: grafana-bigquery-datasource
    access: proxy
    isDefault: true
    jsonData:
      authenticationType: jwt
      clientEmail: adtech-prj@bq-learn-500822.iam.gserviceaccount.com
      defaultProject: bq-learn-500822
      tokenUri: https://oauth2.googleapis.com/token
      privateKeyPath: /etc/grafana/google-key.json
    editable: true
